# MySQL: create database property_db if missing; ensure server is running and credentials match your install.
spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:57162/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=WYRZhKpirIddKzCypJgKJIXbOexkvibZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8081}
